### PR TITLE
[6.0] Import `Darwin` in files that use `free`

### PR DESCRIPTION
**Pull request by ahoppen**
* **Explanation**: Import `Darwin` in files that use `free` to fix compilation errors in some setups.
* **Scope**: Build-time only
* **Risk**: Very low, no functionality change
* **Testing**: n/a
* **Issue**: rdar://131965190
* **Reviewer**:  @bnbarham

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
