### PR TITLE
Simplify the build servers written written used for BSP integration tests and add test case for BSP integration

### PR DESCRIPTION
**Pull request by ahoppen**
A couple of test-only changes:
- The BSP servers we launch to test the out-of-process BSP integration are written in Python and these scripts duplicated a bunch of logic. Factor all of that out into a `AbstractBuildServer.py` file that is shared between all BSP servers.
- Delete build servers for tests that were removed in https://github.com/swiftlang/sourcekit-lsp/commit/20e3fa368b7047934dd013d52392881cf7e0712a
- We only had tests that launched a `BuildServerBuildSystem` but none that actually launched a `SourceKitLSPServer` to test the full integration. Write a test for that including infrastructure for similar tests in the future using `BuildServerTestProject`
- Rename `BuildServerBuildSystem` to `LegacyBuildServerBuildSystem` in preparation for the next PR which exposes all BSP messages we use internally to the BSP server. (https://github.com/swiftlang/sourcekit-lsp/pull/1689)

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by hamishknight — APPROVED** [review]
Haven't looked too much at the python, but the Swift code looks good

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
