### PR TITLE
Expose all BSP messages used by SourceKit-LSP to BSP servers

### LINKED ISSUE #1173: Implement test list for `BuildServerBuildSystem`
Currently, we don’t support syntactic test discovery from `BuildServerBuildSystem` because `BuildServerBuildSystem` does not implement `testFiles` and `addTestFilesDidChangeCallback`. We would probably need to design a BSP request/notification to implement these methods.

rdar://126493405

### LINKED ISSUE #1226: Figure out how to do background preparation for projects with a BSP build server
To index a target, we need to prepare it (which builds all the Swift modules of its dependencies) and for that we probably need a BSP request to prepare a target. For that, we would probably need to introduce a new BSP request or, alternatively, build the entire target, which will perform unnecessary work like building object files. 

We need to design how this interaction should work.

### PR DESCRIPTION
**Pull request by ahoppen**
The interaction to an out-of-process BSP server still went through the `BuildServerBuildSystem`, which doesn’t forward all messages to the build system and uses the old push-based model for build settings.

If we discover that the BSP server supports the new pull-based build settings model, we now forward all methods to it directly, without going through `BuiltInBuildSystemAdapter`, which has been renamed to `LegacyBuildServerBuildSystem`.

rdar://136106323
rdar://127606323
rdar://126493405
Fixes #1226
Fixes #1173

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by hamishknight — APPROVED** [review]

**Pull request merged**
