### PR TITLE
Fix swiftPublishDiagnosticsDebounceDuration documentation

### PR DESCRIPTION
**Pull request by jayadamsmorgan**
Fix documentation on configuring swiftPublishDiagnosticsDebounceDuration property.

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Great catch. Thank you

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by jayadamsmorgan** [comment]
@ahoppen I apologize, looks like I messed up something here, the PR didn't get merged I think

**Comment by ahoppen** [comment]
Thanks for the ping @jayadamsmorgan. I must have indeed forgotten about it.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
