### PR TITLE
Enable sanitizer jobs

### PR DESCRIPTION
**Pull request by ahoppen**
A bunch of changes to enable TSAN on Linux and macOS and UBSAN on macOS. Fixes a few technical issues found by the sanitizers.

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test Linux

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74216

@swift-ci Please test

**Pull request closed without merging**
