### PR TITLE
[6.0] Add configuration files for SourceKit-LSP

### PR DESCRIPTION
**Pull request by ahoppen**
- **Explanation**: Introduce configuration files that can be used to set various options for SourceKit-LSP.
- **Scope**: Setting any of the non-standard options in SourceKit-LSP
- **Risk**: Fairly low, the standard SourceKit-LSP without any options that most people use, is not affected
- **Testing**: Added test cases
- **Issue**: #786, #1475, rdar://129662080, rdar://113099964, rdar://130280855
- **Reviewer**: @bnbarham and @hamishknight on https://github.com/swiftlang/sourcekit-lsp/pull/1535, https://github.com/swiftlang/sourcekit-lsp/pull/1533, https://github.com/swiftlang/sourcekit-lsp/pull/1534, https://github.com/swiftlang/sourcekit-lsp/pull/1536

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
